# Generated by Django 4.2.5 on 2023-10-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SchoolAdmin', '0001_initial'),
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('person_type', models.CharField(choices=[('M', 'Merchant'), ('C', 'Customer'), ('A', 'School Admin')], max_length=1)),
                ('customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('customer_wallet', models.FloatField(default=0.0)),
                ('school_admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.schooladmin')),
                ('transaction_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.transactions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
