# Generated by Django 4.2.7 on 2023-12-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SchoolAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('person_type', models.CharField(choices=[('M', 'Merchant'), ('C', 'Customer'), ('A', 'School Admin')], max_length=1)),
                ('customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('customer_wallet', models.FloatField(default=0.0)),
                ('school_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.schooladmin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
