# Generated by Django 4.2.5 on 2023-10-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='transaction_history',
        ),
        migrations.AddField(
            model_name='customer',
            name='transaction_history',
            field=models.ManyToManyField(to='Transaction.transactions'),
        ),
    ]
