# Generated by Django 4.2.5 on 2023-10-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Product', '0001_initial'),
        ('Merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('partial_total_amount', models.FloatField()),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_subtotal', models.FloatField(default=0.0)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('check_out_ID', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('payment_method', models.CharField(choices=[('B', 'Online Bank'), ('G', 'GCash'), ('C', 'CoD')], max_length=1)),
                ('receive_by_date', models.DateTimeField()),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('merchant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchant.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField()),
                ('cart_subtotal', models.FloatField()),
                ('cart_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.cart')),
                ('product_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product')),
                ('product_quantity_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.productquantity')),
            ],
        ),
    ]
