# Generated by Django 4.2.5 on 2023-10-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('C', 'CoD'), ('B', 'Online Bank'), ('G', 'GCash')], max_length=1),
        ),
    ]
