# Generated by Django 4.2.5 on 2023-10-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_checkout_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('C', 'CoD'), ('G', 'GCash'), ('B', 'Online Bank')], max_length=1),
        ),
    ]
