# Generated by Django 4.2.7 on 2023-12-28 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Merchant', '0001_initial'),
        ('Cart', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_details', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_availability', models.BooleanField()),
                ('product_stock', models.IntegerField()),
                ('merchant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchant.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('product_review_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_Rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.CharField(max_length=1000)),
                ('review_date', models.DateField(default=datetime.datetime(2023, 12, 29, 1, 43, 34, 682980))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
