# Generated by Django 4.2.7 on 2023-12-28 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=1)),
                ('amount', models.FloatField(default=0)),
                ('transaction_date', models.DateField(default=datetime.datetime(2023, 12, 29, 1, 43, 34, 683978))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_history', to='Customer.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_history', to='Merchant.merchant')),
            ],
        ),
    ]
