# Generated by Django 4.2.7 on 2023-12-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('person_type', models.CharField(choices=[('M', 'Merchant'), ('C', 'Customer'), ('A', 'School Admin')], max_length=1)),
                ('courier_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('commission', models.FloatField(default=50.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryPersonnel',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('person_type', models.CharField(choices=[('M', 'Merchant'), ('C', 'Customer'), ('A', 'School Admin')], max_length=1)),
                ('delivery_personnel_ID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourierOrderDp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_delivery_date', models.DateField()),
                ('date_delivered', models.DateField(blank=True, null=True)),
                ('delivery_status', models.IntegerField(default=0)),
                ('courier_ID', models.ManyToManyField(to='DeliveryPersonnel.courier')),
                ('delivery_personnel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryPersonnel.deliverypersonnel')),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.checkout')),
            ],
        ),
    ]
